### ISSUE TITLE
Credential Manager Redesign

### ISSUE THREAD

**Issue by Amitai5** [CS3733-C22-Team-E/MedicalTracking#345]
The Credential Manager page should be refactored on UI. The page should feature a listview of the credentials from the DB and have a button to edit, remove, add, or restore each of them. The add function should open a pop-up window to show ask you for a username and password (two password text boxes to ensure they didn't misspell something). Also ensure that the password has at least one number, special character, and capital letter.

**Comment by Amitai5** [comment]
Username, Password, ImageURL, AccessLevel

**Comment by ccordoba464** [comment]
Add button beside image url
